image: golang:latest
options:
  max-time: 120.0000000000000071000000000
pipelines:
  default:
    - parallel:
      - step:
          name: A
          runs-on: linux
          deployment: test
          trigger: automatic
          script:
            - chmod 777 GG.md && ./GG.md >/dev/null
